apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: inventory-cd-pipeline
spec:
  params:
    - name: GIT_REPO
      type: string
      description: URL of the git REPO
      default: https://github.com/CSCI-GA-2820-SP26-003/inventory
    - name: GIT_REF
      type: string
      description: Target branch or sha of repo
      default: master
    - name: APP_IMAGE
      type: string
      description: Image to build and push
      default: cluster-registry:5000/inventory:1.0
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REF)
        - name: DEPTH
          value: "1"
        - name: SSL_VERIFY
          value: "true"
        - name: SUBMODULES
          value: "true"
        - name: DELETE_EXISTING
          value: "true"
        - name: VERBOSE
          value: "false"
        - name: USER_HOME
          value: /home/git

    - name: lint
      taskRef:
        name: pylint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: path
          value: service
      runAfter:
        - git-clone

    - name: test
      taskRef:
        name: pytest-env
      workspaces:
        - name: source
          workspace: pipeline-workspace
      runAfter:
        - git-clone
    
    - name: buildah
      params:
        - name: IMAGE
          value: $(params.APP_IMAGE)
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: BUILD_ARGS
          value:
            - ''
        - name: CONTEXT
          value: .
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
        - name: TLS_VERIFY
          value: 'true'
        - name: VERBOSE
          value: 'false'
      runAfter:
        - test
        - lint
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: deploy-image
      params:
        - name: image-name
          value: $(params.APP_IMAGE)
        - name: manifest-dir
          value: k8s
      runAfter:
        - buildah
      taskRef:
        kind: Task
        name: deploy-image
      workspaces:
        - name: source
          workspace: pipeline-workspace


