name: CI Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/rofrano/pipeline-selenium:sp26

    # Required services
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python package dependencies
        run: |
          python -m pip install -U pip pipenv
          pipenv install --system --dev

      - name: Run the service locally
        run: |
          echo "\n*** STARTING APPLICATION ***\n"
          gunicorn --log-level=info --bind=0.0.0.0:8080 wsgi:app &
          echo "Waiting for service to stabilize..."
          sleep 5
          echo "Checking service /health..."
          curl -i http://localhost:8080/health
          echo "\n*** SERVER IS RUNNING ***"
        env:
          DATABASE_URI: "postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/testdb"

      - name: Linting
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics
          # test for complexity. The GitHub editor is 127 chars wide
          flake8 service tests --count --max-complexity=10 --max-line-length=127 --statistics
          # Run pylint to catch other PEP8 errors
          pylint service tests --max-line-length=127

      - name: Run unit tests with PyTest
        run: pytest --pspec --cov=service --cov-fail-under=95 --cov-report=xml
        env:
          DATABASE_URI: "postgresql+psycopg://postgres:postgres@postgres:5432/postgres"

      - name: Run Integration Tests
        run: behave
        env:
          DRIVER: "chrome"

      - name: Install packages for Codecov to work
        run: apt-get update && apt-get install -y git curl gpg

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: CSCI-GA-2820-SP26-003/inventory
